# Generated by Django 2.2.5 on 2021-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'female'), (1, 'male')], default=1),
        ),
    ]
